---
title: "Posture effects (Seated vs Semi-standing vs Standing)"
output: html_document
---
```{r}
library(dplyr)
library(tidyr)
library(readxl)
library(ggplot2)
library(lme4)
library(lmerTest)
library(emmeans)
library(here)
library(stringr)

MODE <- "raw"  # "test" or "raw"

in_path <- here("results", MODE, "vicon_QDM_wrists_head_normByShoulders.xlsx")
stopifnot(file.exists(in_path))

df <- read_excel(in_path)
names(df)
```
```{r}
df <- df %>%
  mutate(
    posture = case_when(
      str_detect(video_id, "^SEATED")   ~ "SEATED",
      str_detect(video_id, "^SEMI")     ~ "SEMI",
      str_detect(video_id, "^STANDING") ~ "STANDING"
    ),
    dyad = str_extract(video_id, "D\\d+")
  )

table(df$posture)

```

```{r}

df_wrist_long <- df %>%
  select(dyad, posture,
         P1_QDM_WRISTS_norm,
         P2_QDM_WRISTS_norm) %>%
  pivot_longer(
    cols = c(P1_QDM_WRISTS_norm, P2_QDM_WRISTS_norm),
    names_to = "participant",
    values_to = "value"
  ) %>%
  mutate(
    subject = paste0(dyad, "_", participant),
    value = as.numeric(value)
  )
df_head_long <- df %>%
  select(dyad, posture,
         P1_QDM_HEAD_norm,
         P2_QDM_HEAD_norm) %>%
  pivot_longer(
    cols = c(P1_QDM_HEAD_norm, P2_QDM_HEAD_norm),
    names_to = "participant",
    values_to = "value"
  ) %>%
  mutate(
    subject = paste0(dyad, "_", participant),
    value = as.numeric(value)
  )

```

```{r}
library(afex)
anova_wrist <- aov_ez(
  id = "subject",
  dv = "value",
  within = "posture",
  data = df_wrist_long,
  anova_table = list(correction = "GG", es = "pes")
)

anova_wrist

anova_head <- aov_ez(
  id = "subject",
  dv = "value",
  within = "posture",
  data = df_head_long,
  anova_table = list(correction = "GG", es = "pes")
)

anova_head
```
```{r}
emmeans(anova_wrist, pairwise ~ posture, adjust = "bonferroni")
emmeans(anova_head, pairwise ~ posture, adjust = "bonferroni")
```

